local terminal = require("terminal.mappings")
vim.keymap.set({ "n", "x" }, "<leader>ts", terminal.operator_send, { expr = true })
vim.keymap.set("n", "<leader>to", terminal.toggle)
vim.keymap.set("n", "<leader>tO", terminal.toggle({ open_cmd = "enew" }))
vim.keymap.set("n", "<leader>tr", terminal.run)
vim.keymap.set("n", "<leader>tR", terminal.run(nil, { layout = { open_cmd = "enew" } }))
vim.keymap.set("n", "<leader>tk", terminal.kill)
vim.keymap.set("n", "<leader>t]", terminal.cycle_next)
vim.keymap.set("n", "<leader>t[", terminal.cycle_prev)
vim.keymap.set("n", "<leader>tl", terminal.move({ open_cmd = "belowright vnew" }))
vim.keymap.set("n", "<leader>tL", terminal.move({ open_cmd = "botright vnew" }))
vim.keymap.set("n", "<leader>th", terminal.move({ open_cmd = "belowright new" }))
vim.keymap.set("n", "<leader>tH", terminal.move({ open_cmd = "botright new" }))
vim.keymap.set("n", "<leader>tf", terminal.move({ open_cmd = "float" }))
